CREATE TABLE IF NOT EXISTS TB_BOOK (
    ID INTEGER PRIMARY KEY,
    TITLE TEXT,
    AUTHOR TEXT,
    ISBN TEXT,
    CREATE_DATE TEXT,
    UPDATE_DATE TEXT
);

CREATE TABLE IF NOT EXISTS TB_ISBN (
    ID INTEGER PRIMARY KEY,
    CATEGORY TEXT,
    SUBCATEGORY TEXT,
    NAME TEXT
);